apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespace }}
  source:
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    path: {{ .Values.repo.path }}
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
