apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: kesinti-haritasi
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
